services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./API/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=networkvis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./API
    volumes:
      - ./API:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/networkvis
      - SECRET_KEY=your-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - NETWORKX_MCP_URL=http://networkx-mcp:8001

  networkx-mcp:
    build: ./NetworkXMCP
    volumes:
      - ./NetworkXMCP:/app
    ports:
      - "8001:8001"
    environment:
      - LOG_LEVEL=INFO

  frontend:
    build:
      context: ./frontend
      no_cache: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/build
    ports:
      - "3000:3000"
    depends_on:
      - api
      - networkx-mcp
    environment:
      - NODE_ENV=production

volumes:
  postgres_data:
