[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "networkx>=3.4.2",
    "openai>=1.75.0",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.2",
]
